### ISSUE TITLE
Route definition for buses throws a warning

### ISSUE THREAD

**Issue by akashrajkn** [KnurpsBram/MAS_amsterdam_PT#1]
The current definition for bus routes throws errors like the following: `WARNING: get-distance                  : no link between 20 and 4"`

Needs discussion.

**Comment by akashrajkn** [comment]
Should I use the following routes?

```
route_blue: [3 4 21 22 0 14 19 23 13 10 4 3]
route_purple: [3 9 12 18 15 20 4 3]
route_pink: [3 5 17 7 1 11 16 5 3]
route_green: [3 6 8 2 3]
```

**Comment by florianmohnert** [comment]
okay
