### ISSUE TITLE
Passenger not going to a destination on the route is also picked up

### ISSUE THREAD

**Issue by akashrajkn** [KnurpsBram/MAS_amsterdam_PT#2]
`pick-up-passenger` function picks up a passenger at the bus stop without looking at their destination. For example: 
```
bus route: [ 3 9 8 6 8 2 8 9 3 ]
passenger: [5460 7]  // 7 is the destination of the passenger 5460
```
Above passenger is picked up (at bus stop 3) even though 7 is not in the route.

**Comment by florianmohnert** [comment]
okay so we just say we drop them on centraal if their destination is not on the route? And then at some point they will reach their destination.
